services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: bolt-ai-production
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: "production"
      PORT: "5173"
      RUNNING_IN_DOCKER: "true"
      VITE_LOG_LEVEL: "${VITE_LOG_LEVEL:-debug}"
      DEFAULT_NUM_CTX: "${DEFAULT_NUM_CTX:-32768}"
      GROQ_API_KEY: "${GROQ_API_KEY}"
      HuggingFace_API_KEY: "${HuggingFace_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      OPEN_ROUTER_API_KEY: "${OPEN_ROUTER_API_KEY}"
      GOOGLE_GENERATIVE_AI_API_KEY: "${GOOGLE_GENERATIVE_AI_API_KEY}"
      OLLAMA_API_BASE_URL: "${OLLAMA_API_BASE_URL}"
      XAI_API_KEY: "${XAI_API_KEY}"
      TOGETHER_API_KEY: "${TOGETHER_API_KEY}"
      TOGETHER_API_BASE_URL: "${TOGETHER_API_BASE_URL}"
      AWS_BEDROCK_CONFIG: "${AWS_BEDROCK_CONFIG}"
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
    - ./.env.production:/app/.env.local:ro
    command: >
      sh -lc "pnpm run preview -- --host 0.0.0.0 --port ${PORT:-5173}"
    profiles: ["production"]
